
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_started
    environment:
      RUN_MIGRATIONS: "1"
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
      REDIS_URL: redis://redis:6379/0
    volumes:
      - ./db:/app/db

  celery:
    build: .
    command: celery -A tasks.celery_config worker --loglevel=info
    depends_on:
      redis:
        condition: service_started
    environment:
      RUN_MIGRATIONS: "0"
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
      REDIS_URL: redis://redis:6379/0
    volumes:
      - ./db:/app/db
